---
title: "Epithelial Isolation: Trial 16"
author: "Celeste Valdivia"
date: "2023-08-21"
categories: [epithelial, primaries]
image: "images/trial16/1dps/amp/t16_12_1dps_amp0350.tif"
---

# General Information

1.  **Date and Time:**

August 21, 2023

-   Preparation of epithelial isolation began on 08/21/23 with the quarantine period. Individual S081C001 was set in approximately 60 mL of Autoclaved Artificial Seawater - Gentamicin (0.05%).

August 22, 2023: 0 days post seeding (dps)

-   S081C001 was dissected for zooids on 08/22/23 at 11:30 AM until about 1 PM.

-   Zooids were transferred to an aliqout of tunicate culture media (TCM) in batches of 10 for all 28 zooids.

-   Zooid tissue was seeded at approximately 3 PM.

-   S081C001 was dissected for intact ampullae on 08/22/23 at 1 PM until about 2:30 PM.

-   Ampullae tissue was seed at approximately 3:30 PM.

-   1mL of TCM was added to both T50 cell culture flasks at about 4 PM.

August 23, 2023: 1 dps

-   Flasks were removed from biosaftey cabinet at 11:30 AM and observed at the EVOS inverted microscope.

-   Fungal and bacterial contamination were observed in both flasks. 100% of the media removed. Duplicate rinse with 2 mL of TCM. Replaced media with a final third dose of 2m mL TCM

2.  **Source and Handling of Starting Material:**

-   All tunicates when collected from marina are transported to UWT in 500 mL Nalgene polycarbonate jars filled completely with local marina water. Jars are placed in a cooler to maintain temperature for 30 minute drive back to UWT (from City of De Moines Marina).
-   Upon arrival, tunicates are removed from mussel using a razor blade or kept with substrate and tied to 3'' x 2'' x 1.2 mm glass slide using cotton thread. Tunicates are immediately placed in UWT recirculating artificial seawater system (16 C, 27 PPT).
-   Tunicates are fed every other day (MWF) a mix of commercially available phytoplankton and roti-rich.

Colony Information At Dissection

| date     | colony_id | establishment_date | sampling_location                 | days_at_uwt | stage | zooid_num | health_score |
|---------|---------|--------:|---------|--------:|---------|---------|---------|
| 08/22/23 | S081C001  |         07/26/2023 | De Moines Marina (47.44, -122.34) |          26 | A1-A2 | 28        | 7/10         |

3.  **Cell Isolation Technique:**

-   Epithelial cell isolation occurred mechanically with the use of a pair of 28 G insulin needles.

4.  **Culture Medium Composition:**

<!-- -->

a.  24.5 mL Basal L-15 Media (formulated and initially filtered on 06/12/23, re-filtered after cracking container on 08/21/23) - 5 % FBS - 2% Penicillin-Streptomycin (stock = 100 U)

b.  11 mL concentrated, filtered artificial seawater (stock = 75 PPT)

c.  500 uL HEPES buffer (stock = 20 mM/L)

d.  50 uL Amphotericin B (stock = 250 ug/mL)

```{=html}
<!-- -->
```
5.  **Description of Culture Vessels and Substrates:**

-   Corning 25 cm\^2 Cell Culture Flask, Canted Neck, Tissue Culture Treated, Nonpyrogenic (Cat. No. 430639).
-   No additional coating with substrate.

6.  **Temperature and Environment:**

-   08/22/23: Flasks kept overnight in biosaftey cabinet in UW Tacoma, Tacoma Paper and Stationary (TPS), room 232.

    a.  Temperature: Room Temperature (\~20 C)
    b.  Light: 0
    c.  Humidity: NA

-   08/23/23: Flasks moved to primary cell culture incubator in UW Tacoma, Science Building (SCI).

    a.  Temperature: 18 C
    b.  Light: 0
    c.  Humidity: 91%

7.  **Tissue Seeding Density:**

    -   Document the number of cells seeded in each culture vessel.
    -   Consider testing different seeding densities to observe their effects.

8.  **Observations and Growth Monitoring:**

    -   Regularly document your observations, including cell morphology, attachment, aggregation, or any changes in appearance.
    -   Include photographs if possible.

9.  **Viability and Proliferation:**

    -   Note any signs of cell viability (e.g., cell membrane integrity, absence of debris).
    -   Monitor cell proliferation by documenting changes in cell density over time.

10. **pH and Nutrient Levels:**

    -   If possible, measure and record the pH of the medium during the culture.
    -   Monitor nutrient consumption by measuring glucose or other nutrients if relevant.

11. **Media Changes and Additions:**

-   08/22/23: Added 1 mL of media at 0 dps
-   08/23/23: Removed 100% of media and replaced with 2 mL of TCM.
-   08/25/23:
-   08/29/23: Removed 100% of media and replaced with 2 mL of TCM.

12. **Summary of Results and Outcomes:**

    -   Summarize the overall outcome of the experiment, including whether you observed growth, viability, or any other changes.

13. **Notes and Anomalies:** Document any unexpected events, anomalies, or deviations from your initial plan.

-   08/23/23 (1 dps): Flask contaminated, therefore removed all media and did duplicate rinse with TCM prior to 100% replacement.

14. **Next Steps and Modifications:**

-   Due to observation of contamination at 1 dps, no modifications will be made to the protocol for Trial 17.
-   Biosaftey cabinet to be cleaned:
    a.  70% ethanol all tools in biosaftey cabinet
    b.  70% ethanol all surfaces of biosaftey cabinet
    c.  Use UV sterilization in biosaftey cabinet for 15 minutes
-   Re-implement basic aseptic techniques:
    a.  Thoroughly wash hands and upper arms for at least 20 seconds.
    b.  Avoid using lab coat until it can be laundered.

15. **References and Resources:**

Protocol based on:

::: callout-note 
## Citation

Rabinowitz, C., & Rinkevich, B. (2004). In vitro delayed senescence of extirpated buds from zooids of the colonial tunicate Botryllus schlosseri. Journal of Experimental Biology, 207(9), 1523-1532. [Google Scholar](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C48&q=In+vitro+delayed+senescence+of+extirpated+buds+from+zooids+of+the+colonial+tunicate+Botryllus+schlosseri+&btnG=).

:::

# Protocol
