project:
  type: website
  output-dir: docs
website:
  title: "Celeste Valdivia"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/valeste
format:
  html:
    theme: lux
    css: styles.css

editor: visual

